sudo: required

services:
  - docker

dist: xenial
addons:
  apt:
    packages:
    - docker

env:

cache: npm

os:
  - linux

before_install:

before_script:
  - docker pull localgod/ditspilbuild:latest

script:
  - cd services/frontend
  - docker run --rm -v ${PWD}:/tmp -w /tmp localgod/ditspilbuild:latest firebase --version
  - docker run --rm -v ${PWD}:/tmp -w /tmp localgod/ditspilbuild:latest npm install
  - docker run --rm -v ${PWD}:/tmp -w /tmp localgod/ditspilbuild:latest npm run build
  - if [ "$TRAVIS_BRANCH" = "master" ]; then docker run --rm -v ${PWD}:/tmp -w /tmp localgod/ditspilbuild:latest firebase deploy --token "${FIREBASE_TOKEN}"; fi

after_success:
