version: '3.4'
services:
  devserver:
    container_name: mbn_dev_server
    image: localgod/mbnbuild:latest
    command: ["npm", "run", "serve"]
    working_dir: /tmp/services/frontend/
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
        - type: bind
          source: ./
          target: /tmp
    networks:
      - mbn

networks:
  mbn:
    driver: bridge
